name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: self-hosted

#    strategy:
#      matrix:
#        python-version: [3.12]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'

#- name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install pytest
        
#    - name: Install pip
#      run: |
#          curl -sS https://bootstrap.pypa.io/get-pip.py | python3.12
    - name: Upgrade pip
      run: |
        python3.12 -m pip install --upgrade pip
        - name: verify python & Pip
          run: |
          python3.12 --version
          python3.12 -m pip --version
          
    - name: Run tests
      run: |
        cd src
        python -m pytest addition.py
